### ISSUE TITLE
Collider class requires derived word 'public'

### ISSUE THREAD

**Issue by XanderMooney** [Jauntlet/Jauntlet#1]
Chris has pulled off his magic touch, and now all derived classes of Collider2D requires the keyword `public` infront of Collider2D.

How has he done this?
Why can't we remove it?
Why does this suddenly feel like a legacy system?
Send help.

**Comment by ponyfan88** [comment]
@PlayStation24Chris did you get this?

**Comment by XanderMooney** [comment]
Turns out Chris is the better programmer compared to Kennedy, and this is as intended.
