### ISSUE TITLE
Error handling w/ email sending

### ISSUE THREAD

**Issue by ponyfan88** [Jauntlet/Jauntlet#11]
using std::set_terminate(void method that sends an email) in jauntlet.cpp we can handle all thrown errors with the engine.

https://cplusplus.com/reference/exception/set_terminate/

from chatgpt:

> std::set_terminate is a C++ function that allows you to set a custom termination handler for your program. This handler is invoked when the terminate function is called, typically as a result of an unhandled exception propagating up the call stack. By setting a custom terminate handler using std::set_terminate, you can define your own behavior for how your program should handle uncaught exceptions before it terminates, such as logging error information or performing cleanup actions.

**Comment by XanderMooney** [comment]
fixed with [0983743](https://github.com/XanderMooney/Jauntlet/commit/098374334b52d2163282415ea8c6c92964ff7962)
