### ISSUE TITLE
invisible ui elements hide all elements

### ISSUE THREAD

**Issue by ponyfan88** [Jauntlet/Jauntlet#16]
when any ui element is marked as not visible all other elements will not draw. their draw statements are handled, just spritebatches do not draw.

**Comment by ponyfan88** [comment]
checked once more, spritebatch->draw is called and doesn't do anything, everything else is handled.

**Comment by ponyfan88** [comment]
also happens reguardless of order, and ONLY for text elements

**Comment by XanderMooney** [comment]
@ponyfan88 is this still an issue as of now with your UIBatches changes?

**Comment by XanderMooney** [comment]
fixed when text was fixed -@ponyfan88
