### ISSUE TITLE
UI Text elements don't render

### ISSUE THREAD

**Issue by XanderMooney** [Jauntlet/Jauntlet#18]
Text elements within the UI does not render at all.

**Comment by XanderMooney** [comment]
This issue has been exemplified by Text rendering changes - higher on my todo list now

**Comment by ponyfan88** [comment]
@XanderMooney iirc you wanted this assigned to me, but assigned it to yourself, was that correct?

**Comment by XanderMooney** [comment]
I had it originally pinned to me, but it may make sense to have it assigned to you now

**Comment by XanderMooney** [comment]
Fixed a little while ago
