### ISSUE TITLE
Cannot resolve positions twice per resize

### ISSUE THREAD

**Issue by PlayStation24Chris** [Jauntlet/Jauntlet#24]
Calling resolvePositions a second time without setting the scale completely breaks UI (scaling and positions just completely break)

**Comment by ponyfan88** [comment]
this is wrong, or at the very least has more conditions that need to be met. i've ran resolvePositions over 5 times before and after setting a scale in a test and nothing has broken. reopen this if you need to, but this doesnt seem to be an issue.
