### ISSUE TITLE
Animatable Sprites in UI system

### ISSUE THREAD

**Issue by XanderMooney** [Jauntlet/Jauntlet#28]
As title states, being able to control animations within the UI may prove vital, not only for systems in our current game, but general purpose UI.

**Comment by ponyfan88** [comment]
attempted to add in [e1f2be9](https://github.com/XanderMooney/Jauntlet/commit/e1f2be93761bb4693801b2eb0b5a4dc8345e6bb3), let me know how that goes @XanderMooney

**Comment by XanderMooney** [comment]
Fully implemented by @ponyfan88 in [805b510](https://github.com/XanderMooney/Jauntlet/commit/805b510d67463e2c32501746fee460fc7ce296b3)
