### ISSUE TITLE
You cannot control the size of UITextElements

### ISSUE THREAD

**Issue by XanderMooney** [Jauntlet/Jauntlet#32]
Currently, the size of a text element managed by UI is completely controlled by the UI manager, meaning the user has no control over the size of the text element; this quickly leads to cases where the text is simply too big for what the user wants the UI to look like.

**Comment by ponyfan88** [comment]
implemented with [c8571f6](https://github.com/XanderMooney/Jauntlet/commit/c8571f6c500004e62c9449556aed4a90cebb3764)
