### ISSUE TITLE
selected tile outline may not update until mouse is moved

### ISSUE THREAD

**Issue by ponyfan88** [Jauntlet/Jauntlet#35]
as title says, if your tile outline has changed colors, it wont change back to white until after the mouse moves.

**Comment by XanderMooney** [comment]
This is a scoundrills issue not a Jauntlet issue, however it was fixed in [c04c01e](https://github.com/XanderMooney/Scoundrills/commit/c04c01eb12ac2a6d363579e500de7a71fb1e025b) of scoundrills.
