### ISSUE TITLE
Centered UI text is not centered fully

### ISSUE THREAD

**Issue by XanderMooney** [Jauntlet/Jauntlet#37]
The position is off only a little bit, should be just some tweaking to it.
![image](https://github.com/XanderMooney/Jauntlet/assets/113313704/60a3d775-e7df-4bb3-9c0e-27210a294a67)

**Comment by ponyfan88** [comment]
most text related issues with positioning and sizing were fixed in [0a2061f](https://github.com/XanderMooney/Jauntlet/commit/0a2061fefc6a3dacff619718975c6ba66f6e97eb) and [f280b77](https://github.com/XanderMooney/Jauntlet/commit/f280b77d7ab506ca49ecd4caa96eba8fda77955a)
