### ISSUE TITLE
If pathfind destination is not found, the implemented logic crashes the game

### ISSUE THREAD

**Issue by PlayStation24Chris** [Jauntlet/Jauntlet#6]
i think your commit "Logic for if pathfind destination is not found" doesnt work xander
![image](https://github.com/XanderMooney/Jauntlet/assets/113357051/db76f9ef-0978-4128-bba2-287075196452)

**Comment by XanderMooney** [comment]
This was due to a simple out of range vector issue that is not present in release mode. Classic VS debug mode.
